ARG PYTHON_VERSION=3.10.13
FROM python:$PYTHON_VERSION

ENV PYTHONPATH=/code

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7680

CMD ["sh", "-c", "exec uvicorn src.app:app --host 0.0.0.0 --port 7680 --root-path \"${ROOT_PATH:-/}\" --reload"]